openapi: 3.0.1
info:
title: Payment Card Validation API
version: '1.0'
paths:
/api/cards/validate:
post:
summary: Validate payment card data
requestBody:
required: true
content:
application/json:
schema:
type: object
properties:
cardNumber:
type: string
expMonth:
type: integer
expYear:
type: integer
required:
- cardNumber
- expMonth
- expYear
responses:
'200':
description: Validation result
content:
application/json:
schema:
type: object
properties:
valid:
type: boolean
errors:
type: array
items:
type: string
cardType:
type: string
cardNumber:
type: string
'400':
description: Bad request